apiVersion: apps/v1
kind: Deployment
metadata:
  name: t79-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: t79-frontend
  template:
    metadata:
      labels:
        app: t79-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          env:
            - name: NEXT_PUBLIC_API_URL
              value: https://{{ .Values.domain }}/api
          ports:
            - containerPort: 3000
