apiVersion: v1
kind: Secret
metadata:
  name: t79-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:{{ .Values.postgres.password }}@t79-postgres:5432/t79ai"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
