apiVersion: v1
kind: Service
metadata:
  name: t79-backend
  namespace: t79
  labels:
    app: t79-backend
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: t79-backend
  ports:
    - name: http
      port: 8000        # service port inside cluster
      targetPort: 8000  # containerPort from Deployment
