apiVersion: v1
kind: Service
metadata:
  name: secops-backend
  namespace: secops
  labels:
    app: secops-backend
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: secops-backend
  ports:
    - name: http
      port: 8000        # service port inside cluster
      targetPort: 8000  # containerPort from Deployment
