apiVersion: v1
kind: Service
metadata:
  name: t79-frontend
  namespace: t79
  labels:
    app: t79-frontend
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: t79-frontend
  ports:
    - name: http
      port: 3000         # Cluster-service port
      targetPort: 3000   # Must match containerPort in Deployment
