apiVersion: v1
kind: Secret
metadata:
  name: secops-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:{{ .Values.postgres.password }}@secops-postgres:5432/secopsai"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
